[build]
  command = "npm run build"
  publish = "dist"
  ignore = "exit 0"

# Disable all build plugins that are not explicitly installed in package.json
 [[plugins]]
  package = "netlify-plugin-one"

    [plugins.inputs]
    port = 80