[build]
  # Tell Netlify to not run build extensions/plugins
  command = "npm run build"
  publish = "dist"

# Configure the 'neon' extension to be disabled during the build process
  [[plugins]]
  package = "netlify-plugin-one"

    [plugins.inputs]
    port = 80